/**
 * export-cctp-gateway-abi.ts — copy the compiled AgentPactCctpGateway ABI into
 * packages/escrow (JSON + a typed `as const` TS export).
 *
 *   npx hardhat compile && npx tsx scripts/export-cctp-gateway-abi.ts
 *
 * contracts/test/AgentPactCctpGateway.abi.test.cjs fails if either file drifts
 * from the compiled artifact.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const artifact = JSON.parse(
  readFileSync(join(root, "artifacts/contracts/cctp/AgentPactCctpGateway.sol/AgentPactCctpGateway.json"), "utf8"),
) as { abi: unknown[] };
const json = JSON.stringify(artifact.abi, null, 2);

writeFileSync(join(root, "packages/escrow/abi/AgentPactCctpGateway.json"), `${json}\n`);
writeFileSync(
  join(root, "packages/escrow/src/cctp-gateway-abi.ts"),
  `// Generated by scripts/export-cctp-gateway-abi.ts from the compiled
// contracts/cctp/AgentPactCctpGateway.sol artifact. Do not edit by hand.
// SPDX-License-Identifier: MIT
export const AGENTPACT_CCTP_GATEWAY_ABI = ${json} as const;
`,
);
console.log(`exported ${artifact.abi.length} ABI entries`);
