#!/usr/bin/env tsx
import { readFile, writeFile } from "node:fs/promises";
import { relative } from "node:path";

type Route = {
  method: string;
  path: string;
  auth: "public" | "auth" | "admin" | "cron";
  source: string;
  schema?: string;
};

const ROOT = process.cwd();
const SOURCES = [
  "apps/api/src/auth.ts",
  "apps/api/src/health.ts",
  "apps/api/src/webhooks.ts",
  "apps/api/src/concierge-relay.ts",
  "apps/api/src/index.ts",
  "apps/api/src/routes/agents.ts",
  "apps/api/src/routes/offers.ts",
  "apps/api/src/routes/needs.ts",
  "apps/api/src/routes/matching.ts",
  "apps/api/src/routes/deals.ts",
  "apps/api/src/routes/fulfillment.ts",
  "apps/api/src/routes/disputes.ts",
  "apps/api/src/routes/payments.ts",
  "apps/api/src/routes/reputation.ts",
  "apps/api/src/routes/intents.ts",
  "apps/api/src/routes/admin.ts",
  "apps/api/src/routes/feedback.ts",
];

const PUBLIC_EXACT = new Set(["/health", "/api/health", "/api/config", "/api/auth/register", "/api/auth/verify", "/api/auth/nonce"]);
const PUBLIC_GET_PREFIXES = [
  "/api/offers",
  "/api/categories",
  "/api/needs",
  "/api/matches/recommendations",
  "/api/deals",
  "/api/agents",
  "/api/agents/online",
  "/api/leaderboard",
  "/api/skills",
  "/api/fulfillment/types",
  "/api/reputation",
  "/api/intents",
];
const CRON_POST_EXACT = new Set([
  "/api/autopilot/run",
  "/api/concierge/run-full-cycle",
  "/api/concierge/queue-welcome",
  "/api/concierge/queue-first-transaction",
]);

function normalizePath(path: string): string {
  return path.replace(/'/g, "").replace(/`/g, "");
}

function isPublicGet(path: string): boolean {
  if (/^\/api\/deals\/[^/]+\/consultation-responses$/.test(path)) return false;
  return PUBLIC_GET_PREFIXES.some((prefix) => path === prefix || path.startsWith(`${prefix}/`));
}

function classifyAuth(method: string, path: string, routeSource: string): Route["auth"] {
  if (path.startsWith("/api/admin/")) return "admin";
  if (/preHandler\s*:\s*app\.authenticate/.test(routeSource)) return "auth";
  if (PUBLIC_EXACT.has(path)) return "public";
  if (path.startsWith("/api/health")) return "public";
  if (method === "GET" && /^\/api\/deals\/[^/]+\/fulfillment\/audit$/.test(path)) return "auth";
  if (method === "GET" && isPublicGet(path)) return "public";
  if (path.startsWith("/api/public/")) return "public";
  if (path === "/health/detailed" || path === "/ready" || path === "/live" || path === "/health/pool") return "public";
  if (method === "POST" && (CRON_POST_EXACT.has(path) || path.startsWith("/api/concierge/relay") || /^\/api\/deals\/[^/]+\/fulfillment\/auto-complete$/.test(path))) {
    return "cron";
  }
  if (path.includes("stripe-webhook")) return "public";
  return "auth";
}

function detectSchema(window: string): string | undefined {
  const names = Array.from(window.matchAll(/([A-Za-z0-9_]+Schema)\.(?:parse|safeParse)/g)).map((m) => m[1]);
  return Array.from(new Set(names)).join(", ") || undefined;
}

function extractRoutes(source: string, file: string): Route[] {
  const routes: Route[] = [];
  const routeRe = /app\.(get|post|patch|put|delete)\s*\(\s*(["'`])([^"'`]+)\2/g;
  let match: RegExpExecArray | null;
  while ((match = routeRe.exec(source))) {
    const method = match[1].toUpperCase();
    const path = normalizePath(match[3]);
    const before = source.slice(0, match.index);
    const line = before.split("\n").length;
    const window = source.slice(match.index, Math.min(source.length, match.index + 1800));
    routes.push({
      method,
      path,
      auth: classifyAuth(method, path, window),
      source: `${file}:${line}`,
      schema: detectSchema(window),
    });
  }
  return routes;
}

function markdown(routes: Route[]): string {
  const generatedAt = new Date().toISOString();
  const rows = routes.map((route) => [
    route.method,
    `\`${route.path}\``,
    route.auth,
    `\`${route.source}\``,
    route.schema ? `\`${route.schema}\`` : "—",
  ]);

  return `# API Route Inventory\n\n` +
    `Generated by \`npm run api:routes\` from Fastify route registrations in source.\n\n` +
    `Generated at: ${generatedAt}\n\n` +
    `Auth classification mirrors the API preHandler in \`apps/api/src/index.ts\`: ` +
    `\`public\` routes bypass API-key auth, \`auth\` routes require agent API-key auth, ` +
    `\`admin\` routes use admin-key checks in their handlers, and \`cron\` routes are intentionally callable by scheduled jobs or have handler-local controls.\n\n` +
    `Total routes: ${routes.length}\n\n` +
    `| Method | Path | Auth | Source | Request schema |\n` +
    `| --- | --- | --- | --- | --- |\n` +
    rows.map((row) => `| ${row.join(" | ")} |`).join("\n") +
    `\n`;
}

async function main() {
  const routes: Route[] = [];
  const missing: string[] = [];
  for (const file of SOURCES) {
    try {
      const source = await readFile(file, "utf8");
      routes.push(...extractRoutes(source, file));
    } catch {
      missing.push(file);
    }
  }

  routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method) || a.source.localeCompare(b.source));

  const counts = new Map<string, number>();
  for (const route of routes) {
    const key = `${route.method} ${route.path}`;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  const duplicates = Array.from(counts.entries()).filter(([, count]) => count > 1);
  if (duplicates.length > 0) {
    throw new Error(`Duplicate routes found: ${duplicates.map(([key, count]) => `${key} (${count})`).join(", ")}`);
  }

  const outPath = "docs/API_ROUTE_INVENTORY.md";
  await writeFile(outPath, markdown(routes), "utf8");

  const byAuth = routes.reduce<Record<string, number>>((acc, route) => {
    acc[route.auth] = (acc[route.auth] ?? 0) + 1;
    return acc;
  }, {});
  console.log(`API route inventory updated: ${relative(ROOT, outPath)}`);
  console.log(`Routes: ${routes.length} (${Object.entries(byAuth).map(([auth, count]) => `${auth}=${count}`).join(", ")})`);
  if (missing.length > 0) console.warn(`Skipped missing sources: ${missing.join(", ")}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
